#!/usr/bin/env bash
set -e

export PDF_PREFIX="timothee-jourde-"

tmp=$(mktemp -d)
export HOME=$tmp

test -z $NO_CONFIGURE && runhaskell Setup.hs configure
runhaskell Setup.hs build

(
    cd res
    autoprefixer-cli -b "last 90 versions" -o - style.css | cleancss -o style.prefix.min.css
)

mkdir -p lang
dist/build/cv/cv

(
    cd lang
    for src in *.html
    do
	chromium --headless --disable-gpu --print-to-pdf="${PDF_PREFIX}${src%.html}.pdf" "$src"
    done
)

rm -r $tmp
